# Generated by Django 5.1 on 2024-08-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
